spring:
  redis:
    host: localhost
    port: 6379
    password: 1111  # 비밀번호가 없다면 이 줄을 생략
    database: 0  # 기본 Redis 데이터베이스
    lettuce:
      pool:
        max-active: 10  # 최대 활성 연결 수
        max-idle: 10  # 최대 유휴 연결 수
        min-idle: 2  # 최소 유휴 연결 수

  session:
    store-type: redis  # 세션 스토리지를 Redis로 사용
    timeout: 1800s  # 세션 타임아웃 설정 (예: 30분)
    redis:
      flush-mode: immediate  # 세션 변경 시 즉시 Redis에 반영

  cache:
    type: redis  # 캐시를 Redis로 사용
    redis:
      time-to-live: 60000  # 캐시 TTL을 60초로 설정
      cache-null-values: false  # null 값 캐시 방지
      use-key-prefix: true  # 키에 접두어 사용
