spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/todohouseworkDB
    username: postgres
    password: 1379
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  data:
    redis:
      host: redis
      port: 6379
      timeout: 60000

  cache:
    type: redis
    redis:
      time-to-live: 3600000
      key-prefix: "myapp::"

  mail:
    host: smtp.gmail.com
    port: 587
    username: palgalow@gmail.com
    password: slay01379
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8080

